### PR TITLE
Gh pages develop

### PR DESCRIPTION
**Pull request by nosy79**

### CODE REVIEW

**Comment by olf42** [comment]
My change made in https://github.com/codingdavinci/codingdavinci.de/pull/234/commits/9c2f5b46a63a013985a7d31c4b2f85d61f703a9a seems to be reverted. I changed the date to 16th of June but here it was changed back to June 19th.. https://github.com/codingdavinci/codingdavinci.de/pull/234/files/9c2f5b46a63a013985a7d31c4b2f85d61f703a9a..287c18834cd11c4f71b5c5b7ec93f08ce6d87721

**Comment by nosy79** [comment]
Very strange...it seems the sentence

Daneben gibt es weitere Neuigkeiten und Einblicke in die Vorbereitungen auch auf Twitter unter <a href="https://twitter.com/cdvost">@cdvost</a>.</p>

was new, too and it survived...at least in the preview...lets see what I can do...

**Comment by nosy79** [comment]
Ok...redelivered the pages to the web site hoster...afterwards it was consistent - 19.6. and the new sentence.
I changed the date again...

**Comment by olf42** [comment]
It's correct now. Thank you for your effort! :)

**Pull request merged**
